### ISSUE TITLE
Not working with Minecraft 1.21/Bluemap 5.1

### ISSUE THREAD

**Issue by Jaymus3** [TechnicJelle/BlueMapMCMapSync#4]
Very cool addon!  I tried to test it with my 1.21 server with Bluemap 5.1 and it is unable to load.  I get the following stacktrace:
`Console
de.bluecolored.bluemap.common.addons.AddonException: No bluemap.addon.json found in 'plugins/BlueMap/addons/BlueMapMCMapSync-0.1.jar'
at de.bluecolored.bluemap.common.addons.Addons.tryLoadAddon(Addons.java:76) ~[?:?]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at de.bluecolored.bluemap.common.addons.Addons.tryLoadAddons(Addons.java:67) ~[?:?]
at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:127) ~[?:?]
at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:113) ~[?:?]
at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[?:?]
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

I'd also happily test the version you referenced in #3 that automatically syncs map discovery if you provide a built version or build instructions.

**Comment by TechnicJelle** [comment]
This is a paper plugin, not a native BlueMap addon.
You should put it in your plugins folder, not inside BlueMap's own addons folder.

Also, I don't think Paper is out yet for 1.21...
And I don't support Spigot... You could try it, though. Maybe it works?

**Comment by TechnicJelle** [comment]
Thank you for wanting to test it! I had almost forgotten about it already, haha...
With so many other plugins to maintain, it had slipped under my radar...
Please let me know if it all behaves exactly like you would expect in the comments on that PR! :D

You can download the latest build of #3 here: https://github.com/TechnicJelle/BlueMapMCMapSync/actions/runs/8710914384/job/23893863896?pr=3

It'll then create a config for you, in which you can enable the automatic discovery mode.
You can reload the config using `/bluemap reload`
