### ISSUE TITLE
1.21.1+ Support?

### ISSUE THREAD

**Issue by RFlintstone** [TechnicJelle/BlueMapMCMapSync#5]
Any chance this plugin will support 1.21.1+ (Paper) in the near future?
Currently getting this issue:

```bash
[14:33:53 ERROR]: Command exception: /bmdiscover
org.bukkit.command.CommandException: Unhandled exception executing command 'bmdiscover' in plugin BlueMapMCMapSync v0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1586) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/flowpowered/math/vector/Vector2i
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.Square.init(Square.java:47) ~[BlueMapMCMapSync-0.1.jar:?]
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.Square.<init>(Square.java:33) ~[BlueMapMCMapSync-0.1.jar:?]
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.commands.BMDiscover.onCommand(BMDiscover.java:75) ~[BlueMapMCMapSync-0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more
Caused by: java.lang.ClassNotFoundException: com.flowpowered.math.vector.Vector2i
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.Square.init(Square.java:47) ~[BlueMapMCMapSync-0.1.jar:?]
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.Square.<init>(Square.java:33) ~[BlueMapMCMapSync-0.1.jar:?]
        at BlueMapMCMapSync-0.1.jar/com.technicjelle.bluemapmcmapsync.commands.BMDiscover.onCommand(BMDiscover.java:75) ~[BlueMapMCMapSync-0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

**Comment by TechnicJelle** [comment]
I get similar issues.
This is likely not caused by this plugin not supporting new Minecraft versions, but it doesn't support new BlueMap versions.
I will update the dependencies and see if that fixes it!

**Comment by TechnicJelle** [comment]
It works again on my test server (`paper-1.21.1-131` with `bluemap-5.5-paper`)
Please try out this test build: https://github.com/TechnicJelle/BlueMapMCMapSync/actions/runs/11980871259
And let me know if it works again for you!

**Comment by RFlintstone** [comment]
> It works again on my test server (`paper-1.21.1-131` with `bluemap-5.5-paper`)
> Please try out this test build: https://github.com/TechnicJelle/BlueMapMCMapSync/actions/runs/11980871259
> And let me know if it works again for you!

Thanks for updating! It doesn't seem to give an error anymore so I'm guessing it works now.
BlueMap sadly is to resource intensive for my pi 4b so whenever I can get it to work properly I'll make sure to test this plugin again. 🙂

**Comment by TechnicJelle** [comment]
Then I have published the release! https://github.com/TechnicJelle/BlueMapMCMapSync/releases/tag/v0.2
Thank you for the bug report, and enjoy this new fixed version :)
